sudo: false

language:
  - python

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5

before_install:
    - pip install --upgrade pytest

install:
  - pip install pytest-cov python-coveralls
  - pip install -r requirements.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv --cov swisstool;
    else py.test -vv;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false

